# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c87ebe84606563d0c235126fc8cd439dfdb2c9c9f91069238be41afd7014098f1dd47785961052682111ad6bfd5bb673ba5700bb413a917b411be7a855387f18

test:
  secret_key_base: 07cf9da1968e3fbf163d0612071016e269428fb3ae9366bfb08894298b8056f1e61c7839f05a820dc1ef52962538681622f19d81ce6072f5d9e280fc0ca5bdbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
