require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SolarGardensController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # SolarGarden. As you add validations to SolarGarden, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SolarGardensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all solar_gardens as @solar_gardens" do
      solar_garden = SolarGarden.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:solar_gardens)).to eq([solar_garden])
    end
  end

  describe "GET show" do
    it "assigns the requested solar_garden as @solar_garden" do
      solar_garden = SolarGarden.create! valid_attributes
      get :show, {:id => solar_garden.to_param}, valid_session
      expect(assigns(:solar_garden)).to eq(solar_garden)
    end
  end

  describe "GET new" do
    it "assigns a new solar_garden as @solar_garden" do
      get :new, {}, valid_session
      expect(assigns(:solar_garden)).to be_a_new(SolarGarden)
    end
  end

  describe "GET edit" do
    it "assigns the requested solar_garden as @solar_garden" do
      solar_garden = SolarGarden.create! valid_attributes
      get :edit, {:id => solar_garden.to_param}, valid_session
      expect(assigns(:solar_garden)).to eq(solar_garden)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SolarGarden" do
        expect {
          post :create, {:solar_garden => valid_attributes}, valid_session
        }.to change(SolarGarden, :count).by(1)
      end

      it "assigns a newly created solar_garden as @solar_garden" do
        post :create, {:solar_garden => valid_attributes}, valid_session
        expect(assigns(:solar_garden)).to be_a(SolarGarden)
        expect(assigns(:solar_garden)).to be_persisted
      end

      it "redirects to the created solar_garden" do
        post :create, {:solar_garden => valid_attributes}, valid_session
        expect(response).to redirect_to(SolarGarden.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solar_garden as @solar_garden" do
        post :create, {:solar_garden => invalid_attributes}, valid_session
        expect(assigns(:solar_garden)).to be_a_new(SolarGarden)
      end

      it "re-renders the 'new' template" do
        post :create, {:solar_garden => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested solar_garden" do
        solar_garden = SolarGarden.create! valid_attributes
        put :update, {:id => solar_garden.to_param, :solar_garden => new_attributes}, valid_session
        solar_garden.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested solar_garden as @solar_garden" do
        solar_garden = SolarGarden.create! valid_attributes
        put :update, {:id => solar_garden.to_param, :solar_garden => valid_attributes}, valid_session
        expect(assigns(:solar_garden)).to eq(solar_garden)
      end

      it "redirects to the solar_garden" do
        solar_garden = SolarGarden.create! valid_attributes
        put :update, {:id => solar_garden.to_param, :solar_garden => valid_attributes}, valid_session
        expect(response).to redirect_to(solar_garden)
      end
    end

    describe "with invalid params" do
      it "assigns the solar_garden as @solar_garden" do
        solar_garden = SolarGarden.create! valid_attributes
        put :update, {:id => solar_garden.to_param, :solar_garden => invalid_attributes}, valid_session
        expect(assigns(:solar_garden)).to eq(solar_garden)
      end

      it "re-renders the 'edit' template" do
        solar_garden = SolarGarden.create! valid_attributes
        put :update, {:id => solar_garden.to_param, :solar_garden => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solar_garden" do
      solar_garden = SolarGarden.create! valid_attributes
      expect {
        delete :destroy, {:id => solar_garden.to_param}, valid_session
      }.to change(SolarGarden, :count).by(-1)
    end

    it "redirects to the solar_gardens list" do
      solar_garden = SolarGarden.create! valid_attributes
      delete :destroy, {:id => solar_garden.to_param}, valid_session
      expect(response).to redirect_to(solar_gardens_url)
    end
  end

end
